### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by lufan131** [Gamer2020/PokemonGameEditor#11]
I'm using a ROM I obtained as Fire Red (U) (Independent), but the tool crashes whenever I try to use things like Pokemon editor, attack editor, saying this. Do you have any help ideas?
![pokemongameeditor](https://cloud.githubusercontent.com/assets/19541161/15487168/18c3026e-2119-11e6-8f97-0201794c00e5.PNG)

**Comment by Gamer2020** [comment]
You seem to be using a different dump. Use 1636 - Pokemon Fire Red (U)(Squirrels).gba

**Comment by lufan131** [comment]
Yes, thanks, it works now.
