### ISSUE TITLE
Pokemon editor crashes on sprite import

### ISSUE THREAD

**Issue by lufan131** [Gamer2020/PokemonGameEditor#13]
Importing sprites with the pokemon editor does this. What causes it? 

![image](https://cloud.githubusercontent.com/assets/19541161/15554256/435db4fa-2291-11e6-8f10-8b3695b01d35.png)

**Comment by Gamer2020** [comment]
Please post the sprite sheet you were trying to insert.

**Comment by lufan131** [comment]
![1](https://cloud.githubusercontent.com/assets/19541161/15609878/6998b272-23f0-11e6-8420-73f66c4314e2.png)
It was this Turtwig sprite.

**Comment by Gamer2020** [comment]
The sprites don't match each other. The sprites should be the same except for colors. Here is a resource of already created sprites you can use: http://www.pokecommunity.com/showthread.php?t=267728
