### ISSUE TITLE
Move Effects

### ISSUE THREAD

**Issue by i0brendan0** [Gamer2020/PokemonGameEditor#14]
A lot of the moves effects are just numbers but they can be easily known. Can you make the move effects drop down list to read from a txt file? That way each number effect that can be known is able to easily be changed? aTack has a .dat file that basically is exactly what I mean.

**Comment by Gamer2020** [comment]
I can do that when I get a chance.

**Comment by Gamer2020** [comment]
Done, download the latest beta.
