### ISSUE TITLE
Can't edit custom egg cycles

### ISSUE THREAD

**Issue by i0brendan0** [Gamer2020/PokemonGameEditor#16]
The box used for custom egg cycles doesn't "open" up for use. All other boxes of similar nature work except for that one. Not sure if it works normally cause I expanded the Pokemon.

P.S. Thanks for the move effects text file.

P.P.S. Nothing personal but before closing an issue, maybe wait until confirmation from the user, or after a couple days of not replying. That way another issue doesn't need to be opened up to continue the discussion.

P.P.P.S. The PSS Split was working perfectly before expanding the moves. It might have been from the move table hack option but I haven't tried without it yet.

P.P.P.P.S. How about a function to repoint and expand the move table? That way one doesn't have to manually do it or have to change the offsets in another program (G3HS I think it is) just to do so.

**Comment by i0brendan0** [comment]
I meant to say "sound move table" for the PPPS

**Comment by Gamer2020** [comment]
I'll look into those things when I get a chance. Also...

3. **The creators of this program have no obligation to offer support of any kind for this program. Any support offered is done as a courtesy with no standard expentancy of quality.** Support is currently offered through the Github page.
