### ISSUE TITLE
FireRed PSS Split Move Fix

### ISSUE THREAD

**Issue by i0brendan0** [Gamer2020/PokemonGameEditor#17]
There is a problem with the implementation of extra moves with PGE if someone already has the PSS split. 

At 0x3ED3C on a regular Fire Red rom, there is a pointer to the move data. If someone has used the PSS split, it no longer is a pointer (at least for me it isn't). Adding moves through PGE puts a pointer back in that spot which breaks the PSS split, making every damaging move do 1 damage.

What I would do is have the thing check to see if 0x3ED3C (or in the end each change) is a pointer, and if it isn't, it doesn't edit those bytes.

Now I only tested it without Jambo's move hack so I'm not sure if that changes other needed bytes.

If you leave this issue open long enough I can put my findings on it in a comment when I get around to it.

**Comment by Hikiruka** [comment]
How's the progress on this ?

**Comment by Gamer2020** [comment]
I work 50 hours a week so this is not a priority. I recommend using the Pokemon-Emerald-Battle-Engine-Upgrade project.

**Comment by Hikiruka** [comment]
alright

**Comment by Gamer2020** [comment]
After some testing and thinking, I have determined that the Fire Red PSS split patch is buggy and should not be used. I will not add support for a buggy patch. I am also a believer that people should be moving away from Fire Red and to Emerald. I recommend using the Pokemon-Emerald-Battle-Engine-Upgrade project if you want more attacks and a PSS system that works properly.
