### ISSUE TITLE
Dunno how to see differ the name of each item and pokemon

### ISSUE THREAD

**Issue by LusciousLau** [Gamer2020/PokemonGameEditor#18]
![poke](https://cloud.githubusercontent.com/assets/14839192/17626090/5dd418f2-60de-11e6-8c93-9cd1739cf2da.png)

**Comment by Gamer2020** [comment]
Most likely you are using an incorrect dump. Try 1986_-_Pokemon_Emerald__U__TrashMan

**Comment by Gamer2020** [comment]
No response after 2 months
