### ISSUE TITLE
Attack and Ability Editors dropping an error with Pokemon Ruby (AXVE)

### ISSUE THREAD

**Issue by LOuroboros** [Gamer2020/PokemonGameEditor#2]
Hi.
I'm using PGE 3.2 and the Attack Editor is dropping an error, just like the Ability one.

Ability Editor's Error:
http://ivpaste.com/v/5eO9PwCo

Attack Editor's Error:
http://ivpaste.com/v/I2sUDxIR

**Comment by Gamer2020** [comment]
Nothing seems to be wrong with the program. Simply add missing offsets to the ini. As an alternative you can use Fire Red or Emerald which are better rom bases when compared to Ruby.
