### ISSUE TITLE
Edited pokemon can't evolve now

### ISSUE THREAD

**Issue by AshleyZX** [Gamer2020/PokemonGameEditor#20]
Hi, I have a little problem with the Pokemon Game Editor, I changed some stats to the Kirlia pokemon and now she cant evolve at all

Also im gonna asume that the rest of the pokemons that i edited cant evolve now too  :(

**Comment by Gamer2020** [comment]
Going to need other information in order to figure out what's going on. What exactly did you edit? Which ROM are you using as a base? What other tools have you used on the ROM? Going to be straight up, I don't think PGE is the cause of this.

**Comment by AshleyZX** [comment]
Im using the pokemon lightning yellow room wich is a pokemon red hackrom:
http://pokemonromhack.com/pokemon-lightning-yellow.html

Thats all so far, Just opened the rom and wanted to make gardevoir my main pokemon so i made it a little more stronger, gave her better moves at X levels, more stats and that Kirlia evolves to Gardevoir in level 26 instead of 30. I haven't messed up with the sprites and other stuff of the rom, only pokemons

**Comment by Gamer2020** [comment]
The Pokemon won't evolve because the national Pokedex isn't enabled. It has nothing to do with PGE. Please do not use PGE to alter other peoples work. Play ROM hacks the way they are intended by their creators.

**Comment by AshleyZX** [comment]
Oooooohhhhh, well i just tried to evolve gardevoir and not the others. I had the feeling that i should have tried with other pokemons but oh well, thanks for the answer and the amazing rom editing program,
I love it!

Also is not like im trying to release the ROM and make it look like my own work or anything, I just want it for the nostalgia and try new stuff, Gardevoir is now Psy/fighting, Marowak is ground/steel, Ninetales Fire/Ghost, etc etc...  :D
