### ISSUE TITLE
Can't change Base Experience from 1 to something else.

### ISSUE THREAD

**Issue by Anotherone1** [Gamer2020/PokemonGameEditor#21]
This only occurs for the last new Pokemon I added with PGE, Zekrom. Everything else works, but for some reason, it won't save my changes of the base exp from 1 to 306 for this particular Pokemon. It stays at 1 no matter how much I click save. Is there a way to fix this. It's the last Pokemon on my list, does that have anything to do with the issue.
![error](https://cloud.githubusercontent.com/assets/22271703/18614047/9c5aa6e4-7d54-11e6-815f-8018789c7c79.png)

**Comment by Gamer2020** [comment]
The value should be 1 byte so 255 max.
