### ISSUE TITLE
Cries above Celebi are broken

### ISSUE THREAD

**Issue by LCCoolJ95** [Gamer2020/PokemonGameEditor#22]
When I try to edit the cries of the Hoenn Pokémon in Emerald, I get an error saying:

Input string was not in a correct format.

What am I doing wrong?

**Comment by Gamer2020** [comment]
Are you using the latest beta? What exactly are you trying to do?

**Comment by LCCoolJ95** [comment]
When I repoint the cries (both regular and the ones for growl) for Bulbasaur to Celebi, they work just fine. But for Treecko and above, when I put in an offset, and it's a legitimate offset, when I hit repoint, I get the error. And I am using 3.7.

**Comment by Gamer2020** [comment]
Please use the latest beta...
