### ISSUE TITLE
PGE won't open the Pokemon Editor for any ROM

### ISSUE THREAD

**Issue by DasRuedi** [Gamer2020/PokemonGameEditor#25]
Hi, I was told to come here if I have Problems with PGE and so I did.
I'm using PokemonGameEditor for almost a year now to modify the firered version. Lately when I tried to load another Rom than the firered I was working with, it would show me an error warning as soon as I tried to start the Pokemon Editor function. I could choose between cancel to close it, or ignore to go on and find the Pokemon Editor unable to do anything. Today I made the decision to export all the modded sprites and icons I created yet and put them into a newly downloaded firered Rom since I messed up a few things in the old one. But the PGE wont let me open another Rom and even though I deleted and redownloaded the tool once the problem was still there. I added a screenshot of the error although it's mostly german I think you might get what it's trying to say.

I hope you can help me and look forward to your respond.
Greetings Ruedi. 

![unbenannt-1](https://cloud.githubusercontent.com/assets/24428688/20959487/8921bac2-bc5b-11e6-85fc-e5a5d5905067.jpg)

**Comment by Gamer2020** [comment]
Which other ROM are you trying to open? Are you using the latest beta of PGE? Look in the folder where PGE is, is there an errors.txt file there?

**Comment by DasRuedi** [comment]
first of all thanks for the respond. next thing the roms were the problem, or maybe the place where I got them. I downloaded another firered rom from another website and it worked perfectly. the ones that didn't work, came from emuparadise.me

**Comment by Gamer2020** [comment]
Emuparadise has the right copies. Most programs are made to work with these dumps.
http://www.emuparadise.me/Nintendo_Gameboy_Advance_ROMs/Pokemon_Fire_Red_(U)(Squirrels)/44874
http://www.emuparadise.me/Nintendo_Gameboy_Advance_ROMs/Pokemon_Emerald_(U)(TrashMan)/45224
