### ISSUE TITLE
I do not know if it's a problem, but ... it might make it easier to leave that way

### ISSUE THREAD

**Issue by DjTarma** [Gamer2020/PokemonGameEditor#26]
- In the growth rate at the next release, you can change the numbers to status, like "Erratic, Medium Slow, Fast" because it's hard to select a growth rate in the PGE's actual option. This is very confused and G3HS have this easy option. 
 - And the status like HP,SPD, ATK,DEF can be in the vertical form and in the position:
HP
Atk
Def
SpAtk
SpDef
Spd
 - To rename a extend pokemon, i need to click in the button "Rename pokemon" this option can have a shortcut, pressing enter to rename.
- In the Cry repointer, could have the name of pokemon to repointing, and, a wav importer and repointer for a free offset address. This option would make a big impact on your tool, many people would be drawn to download PGE.

**Comment by Gamer2020** [comment]
1 - I prefer the numbers as it is my personal preference. Accept no imitations!

2 - It's fine how it is now. Changing the order does not change functionality. Maybe down the line it will be reordered but currently no.

3 - Will maybe be done in the future. I will see.

4 - Already being worked on. Please see the latest beta.

**Comment by DjTarma** [comment]
About the growth rate, u can put like the base happiness; "normal(70)
So... "mediumfast (1.000.000)

2016-12-29 16:12 GMT-02:00 TarmaDj . <samuelf843@gmail.com>:
