### ISSUE TITLE
post PGE move relearner bug

### ISSUE THREAD

**Issue by PinkStaircase** [Gamer2020/PokemonGameEditor#27]
Replacing the move in the first move slot with any possible move makes that Pokemon unable to relearn another move at the move relearner.

So if the moves were:
W
X
Y
Z

replacing W with any move will cause 'Not Able' to show up if you want to use the move relearner on that Pokemon again.

This seems to happen for any Pokemon and any move as long as it's the first move slot. It works fine if you use any other move slot.

The only way to work around it now is to swap the first move with another move and then replace it since it's no longer in the first move slot.

**Comment by Gamer2020** [comment]
I am unable to reproduce this. It is working perfectly fine. Also I recommend the following project. https://github.com/KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade
