### ISSUE TITLE
Where do I expand evolutions?

### ISSUE THREAD

**Issue by F-S-B-S** [Gamer2020/PokemonGameEditor#28]
I am new to github and unsure as to how to otherwise send you a message. 
I am on the evolution tab in the Pokemon Editor of the latest (3.7) release of PGE. I have applied the 1.5a patch for MrDollsteak's Attack and Decap, and your tool is working perfectly with it (MrDollsteak advised using it over G3HS in correspondence.)
The maximum number appears to be 5, with no options to expand this number. I want to make the number of evolutions for Eevee 8 in total, rather than 5 (as in the base rom.) I cannot find the option to do this.
![pge](https://cloud.githubusercontent.com/assets/24769322/21473901/abc08868-cae5-11e6-926c-09f67c1f0497.PNG)

**Comment by Gamer2020** [comment]
Edit this in the ini: NumberOfEvolutionsPerPokemon=5

Also please make sure to use the latest beta.
