### ISSUE TITLE
Can't edit Pokémon sharing the same name

### ISSUE THREAD

**Issue by Tetrable** [Gamer2020/PokemonGameEditor#30]
I expanded the Pokémon amount using DizzyEgg's PokéExpansion, and all the entries were created and assigned the name "Bulbasaur". I changed the relevant offsets in PGE's ini, and tested, and it loaded up.

However, when I mouse clicked onto a new entry, it loaded. But if I clicked the Name box, a tab, or anything, it would automatically go to the first entry with the name, who is #1, the original Bulbasaur.

Because of this, I won't be able to change entries for forms of Pokémon sharing the same name. :L

(I am also using the latest files.)

**Comment by Gamer2020** [comment]
Should now be fixed.
