### ISSUE TITLE
Conversion from string "" to type Double is not valid

### ISSUE THREAD

**Issue by Mantager** [Gamer2020/PokemonGameEditor#33]
Using Dollsteak's rom base and the ini for that, on a 32mb rom. none of the offsets in that ini have been changed, repointed, expanded, nothing. I'm on PGE 3.7 atm but this error has occured through all the iterations.

This probably isn't really an issue with the tool as it is a personal issue, but do you have any idea what could be going on?

**Comment by F-S-B-S** [comment]
Have you made sure your rom and the PGE ini are in the same folder with the same name (for example, both named rombase)?

**Comment by Mantager** [comment]
I just did that and although the tool now recognises the ROM name, the error still persists.

**Comment by Gamer2020** [comment]
@Mantager Please let me know if you still need assistance with this issue.

**Comment by Gamer2020** [comment]
I will close this for now. Make sure to use the lastest beta and make sure you aren't missing anything from your ini. I do not recommend the use of that rom base.
