### ISSUE TITLE
Expanding evolutions scrambles evolutions

### ISSUE THREAD

**Issue by F-S-B-S** [Gamer2020/PokemonGameEditor#34]
Editing the number of evolutions does one or two things: it either removes every evolution (expanded to 7 evolutions per pokemon) or makes the pokemon evolve into a seemingly random Pokemon (expanded to 8 evolutions per Pokemon.)

All I did was change the number of evolutions per Pokemon, as instructed.

**Comment by Gamer2020** [comment]
All you did was edit the number of evolutions in the ini?

**Comment by F-S-B-S** [comment]
Yes. Changing the number back to default 5 reverts everything BACK to normal evolutions.

**Comment by Gamer2020** [comment]
Editing the ini only change how the game is read by the program. You actually have to expand the evolutions yourself.
