### ISSUE TITLE
Giving Pokemon More Moves?

### ISSUE THREAD

**Issue by Jirachibi** [Gamer2020/PokemonGameEditor#35]
Okay so 2 questions..Im sorry if these were answered before, I looked and didnt see anything though.

1.) How do i make a pokemon learn more moves? Say I wanted to replace abra with solosis. Abra just learns Teleport by level up, how would I make it so it has an expanded movepool?

2.) There are a bunch of ???'s in between the Johto and Hoenn pokemon. Can I change those into new pokemon or will that screw anything up?

Thanks in advance :) I tried googling but kept getting pages about adding new moves in general, not expanding a moveset :)

**Comment by Gamer2020** [comment]
1) ![addattacks](https://cloud.githubusercontent.com/assets/6243575/22005240/8a773d72-dc2f-11e6-890d-44d45f0a53d2.png)

2) I don't like using those slots.
