### ISSUE TITLE
How to add Fairy?

### ISSUE THREAD

**Issue by Jirachibi** [Gamer2020/PokemonGameEditor#39]
I want to add gen 6 and 7 Pokemon to the games, which is fine. It works fine. The problem, is the fairy type.,  It is in the editor as a type you can choose, but when I make something Fairy and then save, then play the rom to check if it worked, the game crashes. Also, in battle nothing is super effective or not very efective on anything that is the fairy type.

**Comment by Gamer2020** [comment]
You have to add it using something like this: https://github.com/KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade
