### ISSUE TITLE
Invalid cries completely stall the Pokémon Editor

### ISSUE THREAD

**Issue by Squeetz** [Gamer2020/PokemonGameEditor#40]
The fact that the program loads the cry data makes it really slow upon Pokemon load (At least on my PC).
I deleted all the cries in my rom and inserted my own, but then came to fixing the pointers:
Basically, since every Pokémon's cry is now pointing to just tons of FF bytes, trying to edit it in the Pokémon Editor completely freezes the program, so I had to manually repoint them with a hex editor.
After doing so, the Pokémon would load correctly, albeit slowly, because again, some of the custom cries were really big.
The bigger the cries were, the longer it took for the program to load the Pokémon.

I think it might be the cry visualizer that's causing this slowdown?
I'd very much like a version where it isn't visualized, but that might be too much to ask.

**Comment by DizzyEggg** [comment]
That's actually a pretty good idea. Perhaps a checkbox that lets you choose whether to load cries or not?

**Comment by Gamer2020** [comment]
I'm not sure if that will speed it up but I will add that as an option on the main form eventually.

**Comment by Gamer2020** [comment]
Done in latest beta.
