### ISSUE TITLE
Auto-complete not working 

### ISSUE THREAD

**Issue by resetes12** [Gamer2020/PokemonGameEditor#41]
In older versions of the program (3.6), when typing a Pokemon, Attack, etc. the program auto-completed the word. In newer versions (3.8), auto-complete is not working. 

For example, when editing attacks in 3.6 if you typed "Tack" the program auto-completed to "Tackle" but in the current version (3.8) typing "Tack" does not auto-complete. Also, typing "Tackle" and pressing "Change Attack" makes the program crash (unless you press continue to the crash window).

**Comment by Gamer2020** [comment]
Due to the way combo boxes work auto complete was turned off because it caused problems if you have multiple entries of the same name.  Have you tried pressing enter after you type in the move name?

**Comment by resetes12** [comment]
Well, if it's intended that's ok. I understand why, I also had that problem by myself but it made editing attacks easier.

Pressing Enter makes nothing, and then pressing "Change Attack" button makes the program crash. Also creates a buggy attack (this is why it crashes, I suppose).

**Comment by Gamer2020** [comment]
It might be, type name, down arrow,  then enter. I'll check when I can; getting ready for work.

**Comment by Gamer2020** [comment]
Yup it's the following.
1- Type name
2- Press down arrow
3- Press enter
