### ISSUE TITLE
Gamer2020, check this, please!

### ISSUE THREAD

**Issue by DjTarma** [Gamer2020/PokemonGameEditor#42]
I use version 3.7 and after this update ( 3.8) I see that the .ini changed, I simply updated the points according to the paragraph that asks (number of atks, etc) PGE opens normally, pokemon editor/attacks editor normally, but if I open the trainer editor it crashes. I I thought I had inserted something wrong in .ini but I tested it on a fire red vanilla rom and PGE continued to crash. In the cry editor, if I update the number of pokemons in rom from the application itself, I can not insert any cry in the "import" tab. I should insert by an audio editor, like sappy and repoint the offset?
I've been thinking about if you could create a publisher of the stores, being able to insert more than one salesman if you want and also something else that would leave your application still in evidence: An animation editor of the moves. A window containing two screens: One showing your pokemon attacking and the other the foe or the pokemon of a trainer. With separate options such as background, the background that appears when your move will hit the foe, the movement your pokemon will fire a projectile or yourself, the movement that the enemy makes (as if it were shaking or even other Options, such as catching fire, or ice crystals appearing on the foe). And can repoint for new animation offsets.

**Comment by DjTarma** [comment]
And if you could too, an effects editor of moves. But also with a giant table, with innumerable options, as the move inflicts damage normally, inflict damage and not let the enemy leave the battle, freeze without the foe losing hp, paralyze, make the foe quit the battle, or hit the foe According to the speed it has, or the weight, or the number of atk or sp atk. Comparing all of your pokemon's stats to that of the enemy or particularly a stat (appearing option) and if you can also open more slots of effects or edit those that already exist. I'm not demanding this, it's just a hint of a simple guy who uses his amazing tool. You once answered me at pokecommunity and said your tool is better than G3HS, and I confirm that.

**Comment by Gamer2020** [comment]
Check the folder where PGE is. There should be an errors.txt file. Take a look and that will tell you what offsets/values you're missing. 

That's a no go on the animation and move effect editor. I feel those are better handled by just scripting them.

**Comment by Gamer2020** [comment]
What does the errors.txt file say?

**Comment by Gamer2020** [comment]
Haven't heard back from you so closing this for now.
