### ISSUE TITLE
Argument 'RecordNumber' is not a valid value.

### ISSUE THREAD

**Issue by DiveMissile** [Gamer2020/PokemonGameEditor#43]
Basically, when trying to open my Pokemon Emerald with the battle engine upgrade and Poke Expansion in the Pokemon Editor of PGE, it gives me the error, "Argument 'RecordNumber' is not a valid value." When I click ok, it tells me that the rom is running in another program (it's not) and gives me an error message saying that "Value cannot be null. Parameter name: String." with the details saying this: http://pastebin.com/jayMBePE. Clicking continue locks up the program in an uninteractable pokemon editor window. Anyway to help?

**Comment by Gamer2020** [comment]
Check the file in the PGE folder called errors.txt

**Comment by Gamer2020** [comment]
What does the errors.txt file say?

**Comment by Gamer2020** [comment]
Haven't heard back from you so closing this for now.

**Comment by DiveMissile** [comment]
Sorry for not responding soon enough. This error doesn't make an errors.txt file, strangely enough.

**Comment by Gamer2020** [comment]
You ran the script and the program that updates the PGE ini correct? (I can't remember) I'd maybe need a copy of your ROM and ini to figure it out.

**Comment by DiveMissile** [comment]
I did run the script that updated PGE ini. I'll attach a .zip with the rom and ini to this comment, if it helps.

**Comment by Gamer2020** [comment]
Your Pokemon attack table is invalid. Not an issue with PGE.

**Comment by DiveMissile** [comment]
Ah, okay. I'll try to fix that when I can.
