### ISSUE TITLE
Move Tutor compatibility issue

### ISSUE THREAD

**Issue by ThorecGA** [Gamer2020/PokemonGameEditor#44]
I have a little problem with the MoveTutor compatibility in PGE. I installed item expansion and I expand number of move tutors to 50. In the game all works fine, as far I test it. But in PGE, move tutor compatibility doesn't show correctly. I check ini offsets and I think they are correct.

**Comment by Gamer2020** [comment]
Can't look at it till the weekend. Can you please post your ini?

**Comment by ThorecGA** [comment]
Don't worry, I can wait. This is the ini I use, all work fine except move tutor compatibility.

[BPEE]
ROMName=Pokémon Emerald (English)
ItemData=e9cc40
AttackNames=F19B38
TMData=EA94B0
TotalTMsPlusHMs=108
TotalTMs=100
ItemIMGData=ea2c54
NumberOfItems=502
NumberOfAttacks=1024
MoveTutorAttacks=EA9588
NumberOfMoveTutorAttacks=50
PokemonNames=e4b4f8
NumberOfPokemon=905
NationalDexTable=e98518
SecondDexTable=e99338
HoenntoNationalDex=e98c28
PokedexData=e50630
NumberOfDexEntries=817
NumberOfRegionDex=817
PokemonData=e3cf70
AbilityNames=F00E10
NumberOfAbilities=256
Pointer2PointersToMapBanks=84AA4
OriginalBankPointer0=485D60
OriginalBankPointer1=485E44
OriginalBankPointer2=485E58
OriginalBankPointer3=485E6C
OriginalBankPointer4=485E84
OriginalBankPointer5=485EA0
OriginalBankPointer6=485EC0
OriginalBankPointer7=485EE4
OriginalBankPointer8=485F00
OriginalBankPointer9=485F1C
OriginalBankPointer10=485F54
OriginalBankPointer11=485F74
OriginalBankPointer12=485FB8
OriginalBankPointer13=485FE0
OriginalBankPointer14=48603C
OriginalBankPointer15=486070
OriginalBankPointer16=4860AC
OriginalBankPointer17=4860E8
OriginalBankPointer18=4860F0
OriginalBankPointer19=4860F8
OriginalBankPointer20=486100
OriginalBankPointer21=48610C
OriginalBankPointer22=486110
OriginalBankPointer23=486114
OriginalBankPointer24=486118
OriginalBankPointer25=4862C8
OriginalBankPointer26=4863BC
OriginalBankPointer27=486520
OriginalBankPointer28=486528
OriginalBankPointer29=48652C
OriginalBankPointer30=486560
OriginalBankPointer31=486564
OriginalBankPointer32=486568
OriginalBankPointer33=486574
NumberOfMapsInBank0=56
NumberOfMapsInBank1=4
NumberOfMapsInBank2=4
NumberOfMapsInBank3=5
NumberOfMapsInBank4=6
NumberOfMapsInBank5=7
NumberOfMapsInBank6=8
NumberOfMapsInBank7=6
NumberOfMapsInBank8=6
NumberOfMapsInBank9=13
NumberOfMapsInBank10=7
NumberOfMapsInBank11=16
NumberOfMapsInBank12=9
NumberOfMapsInBank13=22
NumberOfMapsInBank14=12
NumberOfMapsInBank15=14
NumberOfMapsInBank16=14
NumberOfMapsInBank17=1
NumberOfMapsInBank18=1
NumberOfMapsInBank19=1
NumberOfMapsInBank20=2
NumberOfMapsInBank21=0
NumberOfMapsInBank22=0
NumberOfMapsInBank23=0
NumberOfMapsInBank24=107
NumberOfMapsInBank25=60
NumberOfMapsInBank26=88
NumberOfMapsInBank27=1
NumberOfMapsInBank28=0
NumberOfMapsInBank29=12
NumberOfMapsInBank30=0
NumberOfMapsInBank31=0
NumberOfMapsInBank32=2
NumberOfMapsInBank33=0
MapLabelData=5A1480
NumberOfMapLabels=213
PokemonFrontSprites=e43250
PokemonBackSprites=e44e90
PokemonNormalPal=e46ad0
PokemonShinyPal=e48710
PokemonAnimations=e43250
FrontAnimationTable=e91090
BackAnimTable=e99a48
AnimDelayTable=e91418
IconPointerTable=e4a350
IconPalTable=e4b170
CryTable=e925c0
CryTable2=e95020
CryConversionTable=e97e08
FootPrintTable=e917a0
PokemonAttackTable=f4a2dc
PokemonEvolutions=e56c50
TMHMCompatibility=ea3bfc
TMHMLenPerPoke=16
MoveTutorCompatibility=ea747c
EnemyYTable=e8f450
PlayerYTable=e90270
EnemyAltitudeTable=e97a80
AttackData=F44C14
ContestMoveData=F04EA4
ContestMoveEffectData=58CDCC
AttackDescriptionTable=F15F00
AbilityDescriptionTable=F00000
StarterPokemon=5B1DF8
StarterPokemonLevel=B1178
StarterEncounterPokemon=32706
StarterEncounterPokemonLevel=32714
AttackAnimationTable=F06F00
BattleFrontierTrainers=5D5ACC
SlateportBattleTentTrainers=5DDA14
VerdanturfBattleTentTrainers=5DE610
FallarborBattleTentTrainers=5DF084
NumberOfBattleFrontierTrainers=300
NumberOfSlateportBattleTentTrainers=30
NumberOfVerdanturfBattleTentTrainers=30
NumberOfFallarborBattleTentTrainers=30
BattleFrontierPokemon=5D97BC
SlateportBattleTentPokemon=5DE02C
VerdanturfBattleTentPokemon=5DEC28
FallarborBattleTentPokemon=5DF69C
NumberOfBattleFrontierPokemon=882
NumberOfSlateportBattleTentPokemon=70
NumberOfVerdanturfBattleTentPokemon=45
NumberOfFallarborBattleTentPokemon=45
BattleFrontierHeldItems=5CECB0
BattleFrontierBanList=611C9A
NumberOfBattlefrontierHeldItems=62
NumberOfTilesInTilset3DF71C=8F
NumberOfTilesInTilset3DF734=15D
NumberOfTilesInTilset3DF74C=17A
NumberOfTilesInTilset3DF764=197
NumberOfTilesInTilset3DF77C=1FF
NumberOfTilesInTilset3DF794=1B8
NumberOfTilesInTilset3DF7AC=16F
NumberOfTilesInTilset3DF7C4=117
NumberOfTilesInTilset3DF7DC=15F
NumberOfTilesInTilset3DF7F4=1C7
NumberOfTilesInTilset3DF80C=A7
NumberOfTilesInTilset3DF824=CA
NumberOfTilesInTilset3DF83C=FE
NumberOfTilesInTilset3DF86C=1FF
NumberOfTilesInTilset3DF884=C6
NumberOfTilesInTilset3DF89C=120
NumberOfTilesInTilset3DF8B4=E7
NumberOfTilesInTilset3DF8CC=19D
NumberOfTilesInTilset3DF8E4=39
NumberOfTilesInTilset3DF8FC=67
NumberOfTilesInTilset3DF914=65
NumberOfTilesInTilset3DF92C=9E
NumberOfTilesInTilset3DF944=79
NumberOfTilesInTilset3DF95C=FF
NumberOfTilesInTilset3DF974=37
NumberOfTilesInTilset3DF98C=47
NumberOfTilesInTilset3DF9A4=43
NumberOfTilesInTilset3DF9BC=1FF
NumberOfTilesInTilset3DF9D4=F7
NumberOfTilesInTilset3DF9EC=52
NumberOfTilesInTilset3DFA04=143
NumberOfTilesInTilset3DFA1C=143
NumberOfTilesInTilset3DFA34=143
NumberOfTilesInTilset3DFA4C=143
NumberOfTilesInTilset3DFA64=26
NumberOfTilesInTilset3DFA7C=3A
NumberOfTilesInTilset3DFA94=25
NumberOfTilesInTilset3DFAAC=8F
NumberOfTilesInTilset3DFAC4=E8
NumberOfTilesInTilset3DFADC=8E
NumberOfTilesInTilset3DFAF4=C3
NumberOfTilesInTilset3DFB0C=9D
NumberOfTilesInTilset3DFB24=EB
NumberOfTilesInTilset3DFB3C=DF
NumberOfTilesInTilset3DFB54=79
NumberOfTilesInTilset3DFB6C=1FF
NumberOfTilesInTilset3DFB84=5F
NumberOfTilesInTilset3DFB9C=52
NumberOfTilesInTilset3DFBB4=44
NumberOfTilesInTilset3DFBCC=95
NumberOfTilesInTilset3DFBE4=3C
NumberOfTilesInTilset3DFBFC=BC
NumberOfTilesInTilset3DFC14=47
NumberOfTilesInTilset3DFC2C=74
NumberOfTilesInTilset3DFC44=FB
NumberOfTilesInTilset3DFC7C=14B
NumberOfTilesInTilset3DFC94=1FF
NumberOfTilesInTilset3DFCAC=19E
NumberOfTilesInTilset3DFCC4=1AA
NumberOfTilesInTilset3DFCDC=15F
NumberOfTilesInTilset3DFCF4=15B
NumberOfTilesInTilset3DFD0C=B0
NumberOfTilesInTilset3DFD24=DC
NumberOfTilesInTilset3DFD3C=19D
NumberOfTilesInTilset3DFD54=34
NumberOfTilesInTilset3DFD6C=42
NumberOfTilesInTilset3DFD84=1CF
NumberOfTilesInTilset3DFD9C=1C2
NumberOfTilesInTilset3DFDB4=5D
NumberOfTilesInTilset3DFDCC=10C
NumberOfTilesInTilset3DFDE4=42
NumberOfTilesInTilset3DFDFC=30
IconPals=DDE1F8
ShadowFronts=1000000
ShadowPals=1002660
ShadowBacks=1007320
JamboLearnableMovesTerm=0000FF
StartSearchingForSpaceOffset=E3CF64
FreeSpaceSearchInterval=100
NumberOfEvolutionsPerPokemon=32
NumberOfEvolutionTypes=255
EvolutionName0=None
EvolutionName1=Happiness
EvolutionName2=Happiness (Day)
EvolutionName3=Happiness (Night)
EvolutionName4=Level
EvolutionName5=Trade
EvolutionName6=Trade w/ Item
EvolutionName7=Item
EvolutionName8=Atk > Def
EvolutionName9=Atk = Def
EvolutionName10=Atk < Def
EvolutionName11=High Personality
EvolutionName12=Low Personality
EvolutionName13=Allow Pokemon Creation
EvolutionName14=Create Extra Pokemon
EvolutionName15=Max Beauty
Evolution0Param=none
Evolution1Param=evolvesbutnoparms
Evolution2Param=evolvesbutnoparms
Evolution3Param=evolvesbutnoparms
Evolution4Param=level
Evolution5Param=evolvesbutnoparms
Evolution6Param=item
Evolution7Param=item
Evolution8Param=level
Evolution9Param=level
Evolution10Param=level
Evolution11Param=level
Evolution12Param=level
Evolution13Param=evolvesbutnoparms
Evolution14Param=level
Evolution15Param=evolvesbasedonvalue
EvolutionName16=Knows Move
Evolution16Param=attack
EvolutionName17=In certain map
Evolution17Param=mapname
EvolutionName18=Level-up at day
Evolution18Param=level
EvolutionName19=Level-up at night
Evolution19Param=level
EvolutionName20=Holding item at day
Evolution20Param=item
EvolutionName21=Holding item at night
Evolution21Param=item
EvolutionName22=Level-up if male
Evolution22Param=level
EvolutionName23=Level-up if female
Evolution23Param=level
EvolutionName24=Level-up if raining
Evolution24Param=level
EvolutionName25=Specific Pokemon in party
Evolution25Param=species
EvolutionName26=Level-up if pokemon with type in party
Evolution26Param=bankandmap
EvolutionName27=Using item if male
Evolution27Param=item
EvolutionName28=Using item if female
Evolution28Param=item
EvolutionName252=Wish Mega Evolution
Evolution252Param=attack
EvolutionName251=Mega Evolution
Evolution251Param=item
EvolutionName255=Revert Megas
Evolution255Param=evolvesbutnoparms
EvolutionName253=Primal Reversion
Evolution253Param=evolvesbasedonvalue
EggMoveTable=32ADD8
EggMoveTableLimiter=70464
TrainerTable=310030
NumberOfTrainers=854
TrainerClasses=30FCD4
NumberOfTrainerClasses=66
TrainerImageTable=305654
NumberOfTrainerImages=92
TrainerPaletteTable=30593C
TrainerMoneyTable=31AEB8
DexSizeTrainerSprite=71
TradeData=338ED0
NumberOfTrades=4
PokedexAlphabetTable=55C6A4
PokedexLightestTable=55C9DA
PokedexSmallestTable=55CCDE
PokedexTypeTable=0
MoveTableHack=True

**Comment by Gamer2020** [comment]
Are you using the latest beta?

**Comment by Gamer2020** [comment]
When you run the expansion leave the number of move tutor moves at 64. The number should always be divisible by 16.

**Comment by ThorecGA** [comment]
Thank you! I didn't know that the number should always be divisible by 16. The next time I'll set the number at 64.
