### ISSUE TITLE
NOT WORKING PGE

### ISSUE THREAD

**Issue by lostindelirium** [Gamer2020/PokemonGameEditor#46]
Mi ROM de pokémon rojo fuego no arranca con este programa, me aparece el mismo error y no se que hacer :(

[

**Comment by Gamer2020** [comment]
Necessito mas informacion para poder ayudarte.

**Comment by Gamer2020** [comment]
No me has contestado pues tengo que cera esto.

**Comment by lostindelirium** [comment]
Perdona por no haberte podido responderte.

Simplemente la cosa es que la app no funciona con mi Rom de Rojo fuego, he
provado en diferentes idiomas y nada, no hay manera y quería ver si tu
podias ayudarme.

Gracias por responderme y perdona la demora.

**Comment by Gamer2020** [comment]
Para Rojo Fuego tienes que usar el dump "1636 - Pokemon Fire Red (U)(Squirrels)" y usar el mas nuevo beta de PGE.

**Comment by lostindelirium** [comment]
Podrías pasarme links si no es mucha molestia? Me ayudaría mucho, Gracias 😊

**Comment by Gamer2020** [comment]
No puedo darte el link. Tienes que buscar lo tu miso.

**Comment by lostindelirium** [comment]
Ah, gracias
