### ISSUE TITLE
Pokédex order editor

### ISSUE THREAD

**Issue by pipecanon** [Gamer2020/PokemonGameEditor#47]
I'm having problem with the Pokedex order editor for Pokemon emerald. I want to put the jhoto starters in de hoenn Dex but when I play the ROM they don't appear in the Pokedex. (I edited the starters of the game to be jhoto's). I also verified to switch the hoenn starters with jhoto's in the Pokedex so there couldn't be a place conflict. Do you know how can I make the jhoto starters appear in the hoenn Pokedex please?

**Comment by Gamer2020** [comment]
You have to edit all the tables not jut the national.
![alt tag](http://i.imgur.com/ECikdom.png)

**Comment by Gamer2020** [comment]
Haven't seen a response so I'm closing this.
