### ISSUE TITLE
Changing names/descriptions doesn't work

### ISSUE THREAD

**Issue by AfrostLord** [Gamer2020/PokemonGameEditor#49]
When I try to change the names/descriptions of moves or pokemon, it just changes to a lot of nonsense

**Comment by Gamer2020** [comment]
I'm going to need more information in order to be able to help you. Are you using a clean ROM or have you used any other programs on the ROM? Which ROM dump are you using?

**Comment by Gamer2020** [comment]
Haven't seen a response so I'm closing this.
