### ISSUE TITLE
Error 63

### ISSUE THREAD

**Issue by Anthroyd** [Gamer2020/PokemonGameEditor#52]
Hi Gamer2020,

I'm having trouble opening the Pokemon Editor tool in PGE. My Emerald ROM loads fine, and I'm able to use all of the other tools. I've been able to use the Pokemon Editor tool recently, but for some reason it has stopped loading properly.

When I click on it, I get [Error 63: Argument 'RecordNumber' is not a valid value.]
An additional box then pops up [Error 75: The process cannot access the ROM file because it is being used by another process.] <-- This isn't true. No other processes are using the file.
A third box then pops up saying [Unhandled exception has occured. Value cannot be null. Parameter name: String.]

At this point, I'm forced to click Quit.

**Comment by Gamer2020** [comment]
Are you using the latest beta?

**Comment by Anthroyd** [comment]
Believe so. I'm using version 3.8. The only changes I made to my ROM between the Pokemon Editor working and not working was inserting some scripts, some mapping, and editing wild Pokemon in AdvancedMap.

**Comment by Gamer2020** [comment]
Please download the latest beta. If you are still getting an error you will have to provide more information to troubleshoot your issue.

**Comment by Anthroyd** [comment]
I think I've solved the problem. I had repointed some of the Pokemon learnset data so Pokemon Editor was having trouble loading it.

Thanks for your time.
