### ISSUE TITLE
Random gui suggestions

### ISSUE THREAD

**Issue by EddyHg80** [Gamer2020/PokemonGameEditor#53]
Heya, I've been using PGE pretty often these days so I came up with several suggestions, let's begin!

Pokemon Editor
![1](https://cloud.githubusercontent.com/assets/9092453/24768237/251d8dca-1b02-11e7-82f0-b1c435441148.PNG)
Could you add a up and down button-arrow to the index box? (I don't know how they are called+I'm italian so, sorry if I can't explain myself sometimes)

Attack editor
![4](https://cloud.githubusercontent.com/assets/9092453/24768434/cdee1cc6-1b02-11e7-8390-c268c0224e8a.PNG)
You put the Decap. all names in the attack selection box, could you move it in the rename attack box like you did in the Pokemon editor?
![3](https://cloud.githubusercontent.com/assets/9092453/24768462/e94a33d8-1b02-11e7-9c53-37fd1b070392.PNG)

![5](https://cloud.githubusercontent.com/assets/9092453/24768484/f957c484-1b02-11e7-9cfb-0e3486237114.PNG)
Could you move the base power down, on top of the accuracy?

![6](https://cloud.githubusercontent.com/assets/9092453/24768522/1c85d766-1b03-11e7-8f11-575577ce2422.PNG)
The first time I used the Attack editor I got confuse because I clicked that save instead of the left one, could you put a box around the description and its save button?

Now some not-gui suggestions :D
Item editor
-Add the awesome "Decap. all names" button :)

Trainer editor
-Add the awesome "Decap. all names" button, in the Trainer Data and in the Trainer Class

Now that I think about it you could add a new "Decap. all names" tool where you can decap many other stuff, like cities, natures and the menù screen ;)

Also in the Pokemon editor, learnable attacks tab, if you put, let's say "pou" for "Pound" but you forget to hit a up or down key to auto select "Pound" and click "change attack" PGE crashes.
You could put the auto complete in the "Change attack" button so it doesn't crashes ;)

Finally I want to thank you for this awesome tool! :D

**Comment by Gamer2020** [comment]
I will look at this when I have some time. I am currently working on something else.

**Comment by EddyHg80** [comment]
No problem :)

**Comment by Gamer2020** [comment]
Haven't forgotten about this. Just busy with other stuff I'm working on.

**Comment by EddyHg80** [comment]
I just noticed that the item editor is also missing the "export" button :)

**Comment by Gamer2020** [comment]
http://gamer2020.ga/?p=248

Due to reasons mentioned in that post I am ending support for PGE at the moment. If you'd like, feel free to add any desired features to PGE and submit a pull request.
