### ISSUE TITLE
no a Issue but if a question

### ISSUE THREAD

**Issue by DIEGODEX** [Gamer2020/PokemonGameEditor#54]
First of all, thanks for creating this tool, it is the best tool that i used and the most complete but only one thing is missing to make it perfect.
I think it's very difficult to create new types with hex.
Will this tool someday have the function of being able to create new types and insert them into the game?.
I will wait your answer.

Sorry for the bad English since it is not my language.

**Comment by Gamer2020** [comment]
You should be using this to add more types:
https://github.com/KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade

**Comment by DIEGODEX** [comment]
Is not there a program that is the same for red fire?
im hacking a fire red version

**Comment by Gamer2020** [comment]
Nope, sorry. That is what you should be using for best results.
