### ISSUE TITLE
Can't use the software on my rom

### ISSUE THREAD

**Issue by Sewef** [Gamer2020/PokemonGameEditor#55]
- Sorry for my English -

Hello, I just download the program and, uh, I just can't use it. I've got the same problem as him : https://github.com/Gamer2020/PokemonGameEditor/issues/50

So, here's the error : https://pastebin.com/fuQDr7LY
I'm using a clean Emerald French rom.
The US version works, so I'm sad.

**Comment by Gamer2020** [comment]
If you look at the roms.ini you'll notice that most of the offsets for the French games are missing. That is why it doesn't work for you.
