### ISSUE TITLE
Can't use any program !

### ISSUE THREAD

**Issue by Boufto24** [Gamer2020/PokemonGameEditor#56]
Hey !
I wanted to add pokémon in my French FireRed version.

I start and I load my ROM, everything's OK.
![screenshot_509](https://cloud.githubusercontent.com/assets/27816813/25234038/2fbfb8ea-25e1-11e7-926c-51c305324b8f.jpg)

But when I click on something : 
![screenshot_510](https://cloud.githubusercontent.com/assets/27816813/25234122/6fcaaf9e-25e1-11e7-8a97-4d95b1191265.jpg)
(Sorry it's in French)

When I click on details it says : 

> --- Fin de la trace de la pile d'exception interne ---
   à Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   à PokemonGameEditor.Pokemonedit.Pokemonedit_Load(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

The error is : 

> Error! NumberOfEvolutionTypes is missing for ROM BPRF!

Is this a problem with the language ?

**Comment by Gamer2020** [comment]
Offsets for the French games are not completely added to the ini at this time. Adding Pokémon to the French games is not supported. Use BPRE if you want to add Pokémon to Fire Red.
