### ISSUE TITLE
MrDollSteak Base ini Issue

### ISSUE THREAD

**Issue by Mogu94** [Gamer2020/PokemonGameEditor#57]
I can't find a thread for this tool on PokeCommunity so I'll put this here.

I am so frustrated with trying to get MrDollSteak's rombase to work in PGE with the ini that you, gamer, linked for it and no matter what I keep getting errors.

http://i.imgur.com/M52qcuW.png

Can you link a working MrDollSteak 1.5a ini that works with PGE 3.8? Because the one you linked when you posted that 3.4 of PGE is out will not work.

**Comment by Gamer2020** [comment]
Hello. There is no thread on PokeCommunity. This is the proper place to post this kind of things. All you would need to do is open errors.txt (Should be in the same location as PGE) and there it will list any values that are missing. You then add them to the ini and everything should be good.

I don't have an ini for the latest version as I feel everyone should be using this: https://github.com/KDSKardabox/Pokemon-Emerald-Battle-Engine-Upgrade

**Comment by Mogu94** [comment]
I get errors from trying to produce a ini with PGEinidump.py for Emerald Battle Engine as well.
https://i.imgur.com/CFayMK1.png
https://i.imgur.com/zMTnz02.png

**Comment by Gamer2020** [comment]
I'm sorry but you will have to bring that up with the creators of the Emerald Battle Engine.
