### ISSUE TITLE
Attack & ability name, descriptions for both and more jumbled messes

### ISSUE THREAD

**Issue by Mogu94** [Gamer2020/PokemonGameEditor#58]
After struggling to get a PGE ini to generate properly for the Emerald Battle Engine for so long, DizzyEgg figured out a solution for me and finally a test.ini was made that'd work for me and not make PGE give off error messages. Well...then I look at the names of attacks and abilities along with the descriptions for both, description for items and pokedex descriptions:
http://i.imgur.com/EoaG1ZA.png
http://i.imgur.com/wF7sKoE.png
http://i.imgur.com/r1eDCFN.png
http://i.imgur.com/ka6cIvA.png
http://i.imgur.com/ksidYUI.png
http://i.imgur.com/m9oF65o.png
http://i.imgur.com/tXeQqHm.png
http://i.imgur.com/EpVQxGC.png
DizzyEgg told me to come and make an issue here since it looks and reads perfectly normal in-game so it's nothing on the engine side.
Here is the Emerald BPEE section of the ini that was generated in case you need to see that. 
https://pastebin.com/ysUUwLf7

I put the freespace in make.py starting at 0x9C0B20 from following these instructions and using the provided patch: http://pokemonhackersonline.com/showthread.php?t=5742 (new to Emerald hacking) Just incase you need to know that as well.
Edit: Tried just now without that freespace patch and have the same result, garbled names and descriptions in PGE only, so it's not that patch somehow causing this.
Edit2: Oh, I am using PGE 3.8 too.

**Comment by Gamer2020** [comment]
Please post a patch of your Rom. Have you tried the latest beta?

**Comment by Mogu94** [comment]
http://bin.smwcentral.net/u/28549/test.ips and now, I haven't tried the latest beta of PGE since that **seemed** to be frowned upon. I'll give that a go though and edit this post with my results.

**Comment by Gamer2020** [comment]
I mean it says it in big letters.

![alt tag](http://i.imgur.com/WrXvXBb.png)

I'll take a look at this when I get a chance.

**Comment by Gamer2020** [comment]
Works fine for me...
![alt tag](http://i.imgur.com/xfklVvT.png)

Use the attached ini
[Mogu94.zip](https://github.com/Gamer2020/PokemonGameEditor/files/956944/Mogu94.zip)

**Comment by Mogu94** [comment]
Still not working for me, oh well, w/e. You seem annoyed ("Works fine for me...") and I'm not looking to take days just to get this to work.

**Comment by Gamer2020** [comment]
Then ROM hacking isn't for you. I'm not going to be taking any more time out of my schedule to help you. Goodbye!
