### ISSUE TITLE
3.6 Pokedex bug

### ISSUE THREAD

**Issue by Ripple884** [Gamer2020/PokemonGameEditor#6]
If you click the pokemon editor button and then select the pokedex tab;  charmander through blastoise cannot be edited and are greyed out.  the same is true for Jigglypuff through kingler.  

tested with a clean ROM to be sure.

**Comment by Gamer2020** [comment]
Which ROM are you using?

**Comment by Ripple884** [comment]
fire red

**Comment by Gamer2020** [comment]
I was just able to reproduce it in Emerald. Ok, I'll check it out in a bit. Thank you!

**Comment by Gamer2020** [comment]
Seems to be an easy fix. Syncing now! Try the latest beta out. Please let me know if you have any more problems. Thanks again!
