### ISSUE TITLE
Issues with expanded ROMs

### ISSUE THREAD

**Issue by Scaen** [Gamer2020/PokemonGameEditor#60]
Hey
I used some of the expanders that come with PGE on my FR ROM (V1.0, E), such es Memory expansion and Pokemon/dex Expansion. When i then tried to re-open the rom (even if its playable and works fine in Adavance Map/Trainer, which i usually use for hacking) in PGE it throws an System.invalidCastExeption (Im using it in German, it says Ausnahmefehler). I figured out, that this could be due to the fact that i didnt changed the Ini-file, so the pointers for some tables etc are not updated there(went to the Offset that is written in the ini-file and just fould 00s) but PGE doesnt tell me to what location it actually repoints beside the dex-entry flags so i cant change the ini. 
Any way to solve this? I guess im just dumb and oversee something i shouldve seen, but i cant really find what to do...

**Comment by Gamer2020** [comment]
Upon using the adders an ini file is created in the same folder as the ROM. That is what should be used with the ROM. Just keep it with the ROM and PGE should be able to open it all. Make sure you are using "1636 - Pokemon Fire Red (U)(Squirrels).gba" for a base ROM.

I do not recommend Fire Red at all. You should use this and other Emerald Projects.
