### ISSUE TITLE
Increased Loading Times and Crashes

### ISSUE THREAD

**Issue by BlackWhiteRobin** [Gamer2020/PokemonGameEditor#61]
I'm using the following on my 32MB BPEE ROM:

-PokeExpnasion [expanded to 1024]
-ItemTmTutorExpansion [expanded to 1024]
-VariousEMFeatures
-EmeraldBattleEngineUpgrade

It was working well with PGE at first but now, I'm having issues:

Since I expanded my ROM to 32MB, I set the ini so that PGE would start looking for free space from 0x1400000. Using the import all spritesheet function, I tried to import all sprites from gen I-IV but got an error halfway. Something about operation failing because of arithmetic overflow. So I tried doing it by hand, importing sprites one by one. But thereafter, still came the problem about the arithmetic overflow for a LOT of sprites.

Oh btw, I'm using the latest commit.

EDIT: Nevermind the errors about arithmetic thingy. It was MrDS sprites' fault. So Now the issue is the random crashes and the long loading time of the program for every operation. :/

Oh and can I suggest a function that imitates the A-Series spritesheet function but for the items instead? Auto-indexing would make importing item images easier. :)

**Comment by Gamer2020** [comment]
http://gamer2020.ga/?p=248

Due to reasons mentioned in that post I am ending support for PGE at the moment. If you'd like feel free to add any desired features to PGE and submit a pull request.
