### ISSUE TITLE
some more minor dex problems in beta build. 

### ISSUE THREAD

**Issue by Ripple884** [Gamer2020/PokemonGameEditor#7]
Machoke's size is wrong, he is also listed as a mole type. 
Same with Machamp, graveler, golem, rapidash, magnemite, megneton, dodrio

weepingbell's type is "flycatcher /n"
ponyta's type is "fire hor/n"
farfetch'd = "wild duc/n"
seel = sealion/n

**Comment by Gamer2020** [comment]
Can you please
![machoke](https://cloud.githubusercontent.com/assets/6243575/14435838/c98877bc-ffe7-11e5-9853-697dd8627545.png)
![weep](https://cloud.githubusercontent.com/assets/6243575/14435839/c9886f56-ffe7-11e5-8e46-31ab118fd884.png)

 provide more information? It does not seem to be happening to me.

**Comment by Ripple884** [comment]
My B.  was using Dollsteak patch again
