### ISSUE TITLE
Repointing Pokemon cry to new offset does not work

### ISSUE THREAD

**Issue by Roxas1123** [Gamer2020/PokemonGameEditor#8]
Using PGE 3.6, I added the Sinnoh starters to the game, and decided to work on Piplup first. Got the sprites and most other components done, however when changing the cry or growl pointer to the new one, which I already inserted into the ROM, I get an unhandled exception error. I tested to make sure it wasn't just the new Pokemon, even on a clean ROM, by changing Bulbasaur's cry to Ivysaur, and I got the same error.
![2016-04-21_19-16-34](https://cloud.githubusercontent.com/assets/5303168/14728838/b9af9922-07f5-11e6-882c-3e11547e3736.png)

**Comment by Gamer2020** [comment]
I just tried to change Bulbasaur's cry to Ivysaur and it worked fine. Can you please provide more information?

**Comment by Roxas1123** [comment]
As it turns out, instead of using a clean ROM, I used a backup, which I had already used Advance Map on. Trying out an _actually_ clean ROM, there are no issues.

**Comment by Roxas1123** [comment]
I came to realize that after I import any new Pokemon cry, such as Turtwig as an example, and then try repointing the cry and growl, for any Pokemon, it starts giving the unhandled exception error. I'm unsure if it's Sappy causing the issue or not. I am still using PGE 3.6, though I see 3.7 is out now, and Sappy 2006 Mod 17.1, if it helps.

**Comment by Gamer2020** [comment]
What offset is the cry at and what is the index for the Pokemon? I need to reproduce the error.

**Comment by Roxas1123** [comment]
I set the offset to 0x7C8F60 and the index would be 1B8.

**Comment by Gamer2020** [comment]
Problem was pretty small. It would only happen on cries that use the cry conversion table. Should be fixed now, try the beta version.

**Comment by Roxas1123** [comment]
Will do. Thank you very much!
