### ISSUE TITLE
Potential noob question

### ISSUE THREAD

**Issue by olivesfang** [Gamer2020/PokemonGameEditor#9]
All of the moves, Pokemon names, items are garbled. Is there a known fix or a setting I'm supposed to tweak before hand? Whatever "Decap. all names" means is beyond me, but that doesn't seem to fix the issue either. Screenshots here: http://imgur.com/a/cfzMF

Thanks for creating such awesome stuff though!

**Comment by Gamer2020** [comment]
I apologize for the late reply. I had replied the email but I guess it didn't go through for some reason.

Are you using version 1.0 of the ROM you are using? Which language is it? Are you using a custom ini or just the default?

**Comment by Gamer2020** [comment]
That ROM should be the right one. 

![checksums](https://cloud.githubusercontent.com/assets/6243575/15271049/4e044b2a-1a04-11e6-9aed-1f160830abf1.png)

See if the checksums match?

**Comment by olivesfang** [comment]
I'm sorry, where do I find that program to calculate these checksums?

**Comment by Gamer2020** [comment]
7-zip

**Comment by olivesfang** [comment]
![image](https://cloud.githubusercontent.com/assets/19187878/15275997/9377e540-1b0d-11e6-9783-0a692ac24a49.png)

Yup, they're the same. 

Could it be a language thing? I have English installed on Win 10, but the laptop is probably somehow Chinese based, I think?

**Comment by Gamer2020** [comment]
Yes, it could be a language issue. It might explain why all the other data seems correct but the strings don't load.

**Comment by olivesfang** [comment]
![image](https://cloud.githubusercontent.com/assets/19187878/15350724/6a02e172-1d0d-11e6-9aac-abfb9f5c9036.png)

My operating system is probably traditional Chinese, even if I set the interface to English. I tried googling the \hFFFF ... that seems to show up in all of the garbled context, but to no avail. Is there a fix you can think of? :( Again, thank you so much for replying.

**Comment by Gamer2020** [comment]
I honestly do not know. You most likely need to install the language pack and change some settings but I've never done it. Try google but it seems like that could be the issue.

**Comment by lufan131** [comment]
Change the system locale to English, I had the same problem, my system was in Japanese. Google the steps to do that, and it fixes the garbled text issue.

**Comment by Gamer2020** [comment]
olivesfang, has your issue been resolved?
